### ISSUE TITLE
Latest version appears to be broken

### ISSUE THREAD

**Issue by adrianparr** [soulwire/fit.js#18]
Hi Justin,

The latest version of fit.js doesn't seem to work.

The version you use on your demo page (http://soulwire.github.io/fit.js/) is working ok.
http://soulwire.github.io/fit.js/fit.js

But the version used in your JSFiddle (http://jsfiddle.net/soulwire/s8zb1fdf/) doesn't seem to work.
https://rawgithub.com/soulwire/fit.js/master/fit.js

I've just downloaded version using Bower and that doesn't work either.

Just thought you should know. Please fix, as it is a really useful library.

Cheers.

**Comment by soulwire** [comment]
Thanks for the heads up. I've reverted the PR that broke this and will resolve the IE issue another way. Appreciate the issue!
