### ISSUE TITLE
Multiple Objects

### ISSUE THREAD

**Issue by nate8684** [soulwire/fit.js#26]
This is most likely a newbie question, so please forgive me. I'm trying to use this script to make all of my images (".fleximg") fit into their corresponding divs (".block).

```
var foo = document.querySelector('.block');
var bar = document.querySelector('.fleximg');

fit(bar, foo, {
    hAlign: fit.CENTER, 
    vAlign: fit.CENTER,
    cover: true,
    watch: true,
    apply: true
});
```

When I run the code, it only adjust the first image and ignores the rest. Any idea why this may be happening, I'm sure I'm misunderstanding the code.

**Comment by nate8684** [comment]
In case anyone else is trying to figure this out, I pushed through and found a solution: 

```
window.onload = function() {

	var examples = document.querySelectorAll( '.pic-wrapper' );
	var i, n, el;
			
	for(var i = 0, n = examples.length; i < n ; i++ ) {
		
		el = examples[i];	
		
        foo = el.querySelector( '.block' );
        bar = el.querySelector( '.fleximg' );
		
		fit(bar, foo, {
		    hAlign: fit.CENTER, // or fit.LEFT, fit.RIGHT
		    vAlign: fit.CENTER, // or fit.TOP, fit.BOTTOM
		    cover: true,
		    watch: true,
		    apply: true
		});
		
	}

};
```

There may be some minor issues with my code, I'm a javascript lightweight.

**Comment by soulwire** [comment]
Hi @nate8684,

Glad you figured it out. You're right, `querySelector` would just select the first matching element so using `querySelectorAll` and applying fit to all matches is the way to go.
